### PR TITLE
fix: add default portRange

### LINKED ISSUE #62: Regression with random port used
Related to https://github.com/nuxt/nuxt/pull/19578

### PR DESCRIPTION
**Pull request by Atinux**
Resolves #62

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -84,6 +84,7 @@ export async function listen(
     port: Number(options_.port),
     verbose: !options_.isTest,
     host: options_.hostname,
+    portRange: [3000, 3100],
```
Comment (pi0) [inline src/index.ts:87]: I think we might only assign port range when there is no explicit `options_.port` (same fix of gpp when a nuxt user for example specifies `port` via config or cli flags, they probably are depending on it and don't expect alternative ranges.)

Comment (Atinux) [reply src/index.ts:87]: Not sure to understand your philosophy here.

Nuxt is already listening to another random port

Comment (Atinux) [reply src/index.ts:87]: Nuxt is always giving the port option anyway

Comment (pi0) [reply src/index.ts:87]: Also we might directly override `alternativePortRange` which is meant for fallback

Comment (Atinux) [reply src/index.ts:87]: How can we overwite `alternativePortRange` since if we define `port` it's not possible 😅 : https://github.com/unjs/get-port-please/blob/73ced5bdea9fb8e23aef7181ac7338260b1e6f58/src/index.ts#L38

Comment (pi0) [reply src/index.ts:87]: [config overrides it](https://github.com/unjs/get-port-please/blob/73ced5bdea9fb8e23aef7181ac7338260b1e6f58/src/index.ts#L41)

Comment (Atinux) [reply src/index.ts]: Pushed `alternativePortRange` instead of `portRange`

Comment (pi0) [reply src/index.ts]: We just simply need to override gpp to force it keep using alternative port range (because listhen adds it's 3000 default). We could also remove it as an alternative fix.

**Review by pi0 — APPROVED** [review]
Thanks for fix and also adding tests!
